// @ts-nocheck
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignUp"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out (access-token in Authorization header) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an event with initial items */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventWithItems"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-profile/phone/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send phone verification OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Phone number in E.164 format (e.g. +15551234567) */
                        phone_e164: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-profile/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search/list public events for discovery or events I host/attend */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of records to return */
                    limit?: components["parameters"]["limit"];
                    /** @description Offset for pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Latitude for geosearch */
                    lat?: number;
                    /** @description Longitude for geosearch */
                    lon?: number;
                    /** @description Radius in kilometers for geosearch */
                    radius_km?: number;
                    /** @description Text search across event title and description */
                    q?: string;
                    /** @description Optional filter by event status */
                    status?: components["schemas"]["EventStatus"];
                    /** @description Filter events starting from this date */
                    dateFrom?: string;
                    /** @description Filter events ending before this date */
                    dateTo?: string;
                    /** @description Filter events whose start time is after the given timestamp */
                    startsAfter?: string;
                    /** @description Filter events whose start time is before the given timestamp */
                    startsBefore?: string;
                    /** @description City name (e.g., 'San Francisco') or string 'lat,lon,radiusKm' */
                    near?: string;
                    /** @description Comma-separated dietary tags (veg,nonveg,mixed) */
                    diet?: string;
                    /** @description Filter by public events (omit for authenticated user's events) */
                    is_public?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEventSummary"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        /** Verify phone using OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone_e164: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Verified */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** Get single event with items & participants */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventFull"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        /** Delete / cancel event */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        options?: never;
        head?: never;
        /** Host updates event details */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventFull"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        trace?: never;
    };
    "/events/{eventId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a **draft** event (draft → published) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventFull"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a **published** event (published → cancelled) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventCancel"];
                };
            };
            responses: {
                /** @description Cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventFull"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a **published** event as completed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventFull"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** Get event capacity availability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Availability data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Availability"];
                    };
                };
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** List join requests (host-only, paginated) */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of records to return */
                    limit?: components["parameters"]["limit"];
                    /** @description Offset for pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Filter by request status */
                    status?: components["schemas"]["JoinRequestStatus"];
                };
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Join requests list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedJoinRequests"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
            };
        };
        put?: never;
        /** Create join request (guest creates pending request + soft hold) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JoinRequestAdd"];
                };
            };
            responses: {
                /** @description Request created with hold */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinRequest"];
                    };
                };
                400: components["responses"]["BadRequestError"];
                404: components["responses"]["NotFoundError"];
                /** @description Capacity unavailable or already requested */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending join requests across my hosted events */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pending join requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedJoinRequests"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/requests/{requestId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve join request (host-only, atomic capacity check) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Request approved, participant created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinRequest"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                /** @description Capacity unavailable */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/events/{eventId}/requests/{requestId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decline join request (host-only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Request declined */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinRequest"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        trace?: never;
    };
    "/events/{eventId}/requests/{requestId}/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move join request to waitlist (host-only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Request waitlisted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinRequest"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        trace?: never;
    };
    "/events/{eventId}/requests/{requestId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cancel join request (guest cancels own request) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Request cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinRequest"];
                    };
                };
                404: components["responses"]["NotFoundError"];
                /** @description Request expired or in invalid state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/events/{eventId}/requests/{requestId}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend hold expiration (host-only, optional) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hold extended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinRequest"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/requests/{requestId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder a waitlisted request (host-only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        waitlist_pos: number;
                    };
                };
            };
            responses: {
                /** @description Reordered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        trace?: never;
    };
    "/events/{eventId}/requests/promote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote first eligible waitlisted request (host-only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Promotion result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            moved?: number;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** List items for event */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        /** Add an item slot to the event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ItemCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                /** @description Item ID */
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        /** Get single item */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Item ID */
                    itemId: components["parameters"]["itemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"];
                    };
                };
            };
        };
        /** Update name/category/per-guest qty */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Item ID */
                    itemId: components["parameters"]["itemId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ItemUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete item slot */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Item ID */
                    itemId: components["parameters"]["itemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List global item catalog */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItemCatalog"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my saved items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserItem"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a saved item template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserItemCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/me/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a saved item template */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserItemUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a saved item template */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/items/{itemId}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                /** @description Item ID */
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign item (self or specified user) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Item ID */
                    itemId: components["parameters"]["itemId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ItemAssign"];
                };
            };
            responses: {
                /** @description Assigned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Unassign item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Item ID */
                    itemId: components["parameters"]["itemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unassigned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** List all participants in an event */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of participants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Participant"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        /** Invite a user or self-RSVP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ParticipantAdd"];
                };
            };
            responses: {
                /** @description Participant added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auto-assign unclaimed items to accepted participants */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default 2 */
                        max_per_user?: number;
                    };
                };
            };
            responses: {
                /** @description Rebalance result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            assigned: number;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participants/{partId}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                /** @description Participant ID */
                partId: components["parameters"]["partId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer RSVP to another user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Participant ID */
                    partId: components["parameters"]["partId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransferParticipantRequest"];
                };
            };
            responses: {
                /** @description Transfer completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransferParticipantResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participants/{partId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                eventId: components["parameters"]["eventId"];
                /** @description Participant ID */
                partId: components["parameters"]["partId"];
            };
            cookie?: never;
        };
        /** Get details of a participant (including RSVP) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Participant ID */
                    partId: components["parameters"]["partId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Participant details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Participant"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        /** Update RSVP or participant details */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Participant ID */
                    partId: components["parameters"]["partId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ParticipantUpdate"];
                };
            };
            responses: {
                /** @description RSVP updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Participant"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        post?: never;
        /** Remove (kick/leave) a participant */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: components["parameters"]["eventId"];
                    /** @description Participant ID */
                    partId: components["parameters"]["partId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Participant removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participants/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk invite participants (host only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        invites?: components["schemas"]["ParticipantBulkAdd"][];
                    };
                };
            };
            responses: {
                /** @description Participants added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participants/{partId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-send invite (host only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invite resent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active pricing plans */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingPlan"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start checkout for a subscription plan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        plan_id: string;
                        /** @enum {string} */
                        provider: "stripe" | "paypal" | "razorpay" | "square" | "lemonsqueezy";
                    };
                };
            };
            responses: {
                /** @description Checkout URL created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutSession"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my active / past subscriptions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subscription"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook endpoint
         * @description Handles checkout.session.*, invoice.*, payment_intent.* events.
         *     Stripe signs the payload; verify in the handler.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's payment methods */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentMethod"][];
                    };
                };
            };
        };
        put?: never;
        /** Add new payment method */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentMethodCreate"];
                };
            };
            responses: {
                /** @description Payment method added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentMethod"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/payment-methods/{methodId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Payment method ID */
                methodId: string;
            };
            cookie?: never;
        };
        /** Get specific payment method */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Payment method ID */
                    methodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentMethod"];
                    };
                };
            };
        };
        /** Update payment method */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Payment method ID */
                    methodId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentMethodUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentMethod"];
                    };
                };
            };
        };
        post?: never;
        /** Remove payment method */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Payment method ID */
                    methodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment method removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/payment-methods/{methodId}/set-default": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Payment method ID */
                methodId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set as default payment method */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Payment method ID */
                    methodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Set as default */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user invoices */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invoice"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices/{invoiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice ID */
                invoiceId: string;
            };
            cookie?: never;
        };
        /** Get specific invoice */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invoice ID */
                    invoiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invoice"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices/{invoiceId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice ID */
                invoiceId: string;
            };
            cookie?: never;
        };
        /** Download invoice PDF */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invoice ID */
                    invoiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                subscriptionId: string;
            };
            cookie?: never;
        };
        /** Get specific subscription */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Subscription ID */
                    subscriptionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subscription"];
                    };
                };
            };
        };
        /** Update subscription */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Subscription ID */
                    subscriptionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubscriptionUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subscription"];
                    };
                };
            };
        };
        post?: never;
        /** Cancel subscription */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Subscription ID */
                    subscriptionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription canceled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/subscriptions/{subscriptionId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                subscriptionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate canceled subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Subscription ID */
                    subscriptionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reactivated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subscription"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_internal/schema-id-param": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dummy endpoint to emit IdParam schema for codegen/validation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns IdParam object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventIdParam"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-profile/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete user profile setup
         * @description Complete the initial profile setup with display name, meal preferences, and location
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileSetupRequest"];
                };
            };
            responses: {
                /** @description Profile setup completed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileSetupResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieve the current user's profile information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description User profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignUp: {
            /** Format: email */
            email: string;
            password: string;
            displayName?: string;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        Location: {
            name: string;
            formatted_address?: string;
            latitude?: number;
            longitude?: number;
        };
        ItemCreate: {
            name: string;
            category?: string;
            per_guest_qty: number;
            /**
             * Format: uuid
             * @description Optional link to global catalog item
             */
            catalog_item_id?: string;
            /**
             * Format: uuid
             * @description Optional link to user's saved item template
             */
            user_item_id?: string;
        };
        /** @description All fields optional for patch */
        ItemUpdate: components["schemas"]["ItemCreate"];
        ItemAssign: {
            /** Format: uuid */
            user_id?: string;
        };
        Error: {
            message: string;
            /** @description Optional machine-readable error code */
            code?: string;
        };
        EventIdParam: {
            /** Format: uuid */
            eventId: string;
        };
        /** @enum {string} */
        JoinRequestStatus: "pending" | "approved" | "declined" | "waitlisted" | "expired" | "cancelled";
        JoinRequestAdd: {
            /** @description Number of guests in the party */
            party_size: number;
            /** @description Optional message to the host */
            note?: string;
        };
        JoinRequest: components["schemas"]["JoinRequestAdd"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            user_id: string;
            status: components["schemas"]["JoinRequestStatus"];
            /**
             * Format: date-time
             * @description When the capacity hold expires (for pending requests)
             */
            hold_expires_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        PaginatedJoinRequests: {
            data?: components["schemas"]["JoinRequest"][];
            nextOffset?: number;
            totalCount?: number;
        };
        Availability: {
            /** @description Total event capacity */
            total: number;
            /** @description Sum of accepted participants party sizes */
            confirmed: number;
            /** @description Sum of pending request holds (not expired) */
            held: number;
            /** @description Remaining capacity (total - confirmed - held) */
            available: number;
        };
        EventCreate: components["schemas"]["EventBase"] & {
            items: components["schemas"]["ItemCreate"][];
        };
        EventBase: {
            title: string;
            description?: string;
            /** Format: date-time */
            event_date: string;
            min_guests: number;
            max_guests?: number;
            /** @description Total event capacity for join requests */
            capacity_total?: number;
            /** @enum {string} */
            status?: "draft" | "published" | "cancelled" | "completed" | "purged";
            /** @enum {string} */
            meal_type: "veg" | "nonveg" | "mixed";
            /**
             * @description Whether event is discoverable by guests
             * @default false
             */
            is_public: boolean;
            location: components["schemas"]["Location"];
        };
        EventWithItems: {
            event?: Record<string, never>;
            items?: components["schemas"]["ItemCreate"][];
        };
        EventSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            event_date: string;
            attendee_count: number;
            /** @enum {string} */
            meal_type: "veg" | "nonveg" | "mixed";
        };
        PaginatedEventSummary: {
            data?: components["schemas"]["EventSummary"][];
            nextOffset?: number;
            totalCount?: number;
        };
        /** @enum {string} */
        EventStatus: "draft" | "published" | "cancelled" | "completed" | "purged";
        EventCore: components["schemas"]["EventBase"] & {
            /** Format: uuid */
            id: string;
            attendee_count: number;
            /** Format: uuid */
            created_by: string;
        };
        EventFull: {
            event: components["schemas"]["EventCore"];
            items: components["schemas"]["Item"][];
            participants: components["schemas"]["Participant"][];
        };
        EventUpdate: components["schemas"]["EventCreate"];
        ParticipantAdd: {
            /** Format: uuid */
            user_id: string;
            /**
             * @description Number of people this participant represents
             * @default 1
             */
            party_size: number;
            /** @enum {string} */
            status?: "invited" | "pending" | "accepted" | "declined" | "maybe";
        };
        ParticipantUpdate: {
            /** @enum {string} */
            status: "invited" | "pending" | "accepted" | "declined" | "maybe";
        };
        Participant: components["schemas"]["ParticipantAdd"] & {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            joined_at?: string;
        };
        ParticipantBulkAdd: {
            /** @description List of participants to invite */
            invites: components["schemas"]["ParticipantAdd"][];
        };
        Item: components["schemas"]["ItemCreate"] & {
            /** Format: uuid */
            id: string;
            required_qty: number;
            assigned_to?: string | null;
        };
        ItemCatalog: {
            /** Format: uuid */
            id: string;
            name: string;
            category?: string;
            unit?: string;
            default_per_guest_qty?: number;
            dietary_tags?: string[];
            description?: string;
        };
        UserItem: components["schemas"]["UserItemCreate"] & {
            /** Format: uuid */
            id: string;
        };
        UserItemCreate: {
            name: string;
            category?: string;
            unit?: string;
            /** @default 1 */
            default_per_guest_qty: number;
            dietary_tags?: string[];
            notes?: string;
        };
        UserItemUpdate: components["schemas"]["UserItemCreate"];
        TransferParticipantRequest: {
            /** Format: uuid */
            new_user_id: string;
            /** @default false */
            carry_items: boolean;
        };
        TransferParticipantResponse: {
            /** Format: uuid */
            old_participant_id: string;
            /** Format: uuid */
            new_participant_id: string;
        };
        BillingPlan: {
            /** Format: uuid */
            id: string;
            price_id: string;
            /** @enum {string} */
            provider: "stripe" | "paypal" | "razorpay" | "square" | "lemonsqueezy";
            name: string;
            amount_cents: number;
            /** @example usd */
            currency: string;
            /** @enum {string} */
            interval: "month" | "year";
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        PaymentIntentResponse: {
            /** Format: uri */
            checkout_url: string;
        };
        Subscription: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            plan_id: string;
            provider_subscription_id: string;
            /** @enum {string} */
            provider: "stripe" | "paypal" | "razorpay" | "square" | "lemonsqueezy";
            /** @enum {string} */
            status: "active" | "trialing" | "past_due" | "canceled" | "incomplete" | "incomplete_expired";
            /** Format: date-time */
            current_period_start?: string;
            /** Format: date-time */
            current_period_end: string;
            /** Format: date-time */
            trial_start?: string;
            /** Format: date-time */
            trial_end?: string;
            cancel_at_period_end?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CheckoutSession: {
            /** Format: uri */
            checkout_url: string;
        };
        /** @description Payload required when the host cancels a published event. Servers must record the reason for audit purposes and may include it in guest notifications.
         *      */
        EventCancel: {
            /** @description Human-readable explanation shown to participants */
            reason: string;
            /**
             * @description If true (default), backend sends cancellation emails / push
             *     notifications. Hosts can suppress notifications for private events.
             *
             * @default true
             */
            notifyGuests: boolean;
        };
        PaymentMethod: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            provider: "stripe" | "paypal" | "razorpay" | "square" | "lemonsqueezy";
            method_id: string;
            is_default: boolean;
            brand?: string;
            last_four?: string;
            exp_month?: number;
            exp_year?: number;
            /** Format: date-time */
            created_at?: string;
        };
        PaymentMethodCreate: {
            /** @enum {string} */
            provider: "stripe" | "paypal" | "razorpay" | "square" | "lemonsqueezy";
            method_id: string;
            /** @default false */
            is_default: boolean;
        };
        PaymentMethodUpdate: {
            is_default?: boolean;
        };
        Invoice: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            subscription_id?: string;
            /** Format: uuid */
            user_id: string;
            invoice_id?: string;
            /** @enum {string} */
            provider: "stripe" | "paypal" | "razorpay" | "square" | "lemonsqueezy";
            amount_cents: number;
            /** @example usd */
            currency: string;
            /** @enum {string} */
            status: "draft" | "open" | "paid" | "void" | "uncollectible";
            /** Format: date-time */
            invoice_date: string;
            /** Format: date-time */
            paid_date?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            invoice_id: string;
            provider_transaction_id?: string;
            /** @enum {string} */
            provider: "stripe" | "paypal" | "razorpay" | "square" | "lemonsqueezy";
            amount_cents: number;
            /** @example usd */
            currency: string;
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "refunded";
            /** Format: date-time */
            paid_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        SubscriptionUpdate: {
            cancel_at_period_end?: boolean;
            /** Format: uuid */
            plan_id?: string;
        };
        ProfileSetupRequest: {
            /**
             * @description User's display name
             * @example John Doe
             */
            display_name: string;
            /**
             * @description Array of dietary preferences
             * @example [
             *       "Vegetarian",
             *       "Gluten-Free"
             *     ]
             */
            meal_preferences?: string[];
            /**
             * @description User's city
             * @example San Francisco
             */
            city?: string;
            /**
             * Format: double
             * @description Latitude coordinate
             * @example 37.7749
             */
            latitude?: number;
            /**
             * Format: double
             * @description Longitude coordinate
             * @example -122.4194
             */
            longitude?: number;
            /**
             * @description Discovery radius in kilometers
             * @default 25
             * @example 25
             */
            discoverability_radius_km: number;
        };
        ProfileSetupResponse: {
            /** @example true */
            success?: boolean;
            /** @example Profile setup completed successfully */
            message?: string;
        };
        UserProfile: {
            /**
             * Format: uuid
             * @description User profile ID (same as user_id)
             */
            id?: string;
            /**
             * Format: uuid
             * @description User ID from auth
             */
            user_id?: string;
            /** @description User's display name */
            display_name?: string;
            /** @description Array of dietary preferences */
            meal_preferences?: string[];
            /** @description User's city */
            city?: string;
            /** @description Whether user is discoverable */
            discoverability_enabled?: boolean;
            /** @description Discovery radius in kilometers */
            discoverability_radius_km?: number;
            /**
             * @description Location precision level
             * @enum {string}
             */
            geo_precision?: "exact" | "city";
            /** @description Whether user has completed initial setup */
            setup_completed?: boolean;
            /**
             * Format: date-time
             * @description Profile creation timestamp
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Profile last update timestamp
             */
            updated_at?: string;
            /** @description E.164 formatted phone number */
            phone_e164?: string | null;
            /** @description Whether the user's phone is verified */
            phone_verified?: boolean;
        };
        ValidationError: {
            /** @example Validation failed */
            error?: string;
            details?: {
                code?: string;
                message?: string;
                path?: string[];
            }[];
        };
    };
    responses: {
        /** @description Access token missing or invalid */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller lacks permission */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with current resource state */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with current resource state */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Maximum number of records to return */
        limit: number;
        /** @description Offset for pagination */
        offset: number;
        /** @description Event ID */
        eventId: string;
        /** @description Item ID */
        itemId: string;
        /** @description Participant ID */
        partId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
