import { StyleSheet, Platform } from "react-native";

/* ===================== Styles ===================== */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  headerContainer: {
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  contentContainer: {
    paddingHorizontal: 12,
    paddingBottom: 24,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  topBarButton: {
    padding: 8,
    borderRadius: 8,
  },
  topBarTitle: {
    fontSize: 14,
    fontWeight: '600',
  },
  topBarSpacer: {
    flex: 1,
  },
  topBarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  eventHeader: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  eventTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
  },
  eventDate: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  chipContainer: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  skeleton: {
    // Add skeleton animation styles if needed
  },
  skeletonTitle: {
    height: 20,
    width: '75%',
    backgroundColor: 'rgba(209, 213, 219, 0.7)',
    borderRadius: 4,
  },
  skeletonDate: {
    marginTop: 12,
    height: 16,
    width: '50%',
    backgroundColor: 'rgba(209, 213, 219, 0.7)',
    borderRadius: 4,
  },
  skeletonChip: {
    height: 24,
    width: 80,
    backgroundColor: 'rgba(209, 213, 219, 0.7)',
    borderRadius: 12,
  },
  tabsContainer: {
    marginTop: 12,
    marginBottom: 8,
    paddingHorizontal: 12,
  },
  tabsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
  },
  tabButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: -1,
  },
  tabButtonActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#3b82f6',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  tabTextActive: {
    color: '#2563eb',
  },
  card: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
    padding: 16,
    marginVertical: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  chipIcon: {
    marginRight: 4,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  chipSky: { backgroundColor: '#e0f2fe' },
  chipEmerald: { backgroundColor: '#d1fae5' },
  chipViolet: { backgroundColor: '#ede9fe' },
  chipTextSky: { color: '#0c4a6e' },
  chipTextEmerald: { color: '#065f46' },
  chipTextViolet: { color: '#5b21b6' },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  pillIcon: {
    marginRight: 4,
  },
  pillText: {
    fontSize: 12,
    fontWeight: '700',
  },
  pillGreen: { backgroundColor: '#dcfce7' },
  pillAmber: { backgroundColor: '#fef3c7' },
  pillRose: { backgroundColor: '#fce7f3' },
  pillIndigo: { backgroundColor: '#e0e7ff' },
  pillTextGreen: { color: '#166534' },
  pillTextAmber: { color: '#92400e' },
  pillTextRose: { color: '#9d174d' },
  pillTextIndigo: { color: '#3730a3' },
  progressContainer: {
    marginTop: 12,
    height: 8,
    width: '100%',
    borderRadius: 4,
    backgroundColor: '#e5e7eb',
  },
  progressBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#000000',
  },
  avatar: {
    height: 40,
    width: 40,
    borderRadius: 20,
  },
  avatarPlaceholder: {
    height: 40,
    width: 40,
    borderRadius: 20,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  rowLeft: {
    fontSize: 14,
    color: '#374151',
  },
  rowRight: {
    fontSize: 14,
    color: '#111827',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  // Tab content styles
  tabContent: {
    gap: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  emoji: {
    fontSize: 12,
  },
  // RSVP styles
  rsvpButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  rsvpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
  },
  rsvpButtonAccepted: {
    backgroundColor: '#16a34a',
    borderColor: 'transparent',
  },
  rsvpButtonAcceptedInactive: {
    backgroundColor: '#f0fdf4',
    borderColor: 'rgba(22, 163, 74, 0.4)',
  },
  rsvpButtonDeclined: {
    backgroundColor: '#dc2626',
    borderColor: 'transparent',
  },
  rsvpButtonDeclinedInactive: {
    backgroundColor: '#fef2f2',
    borderColor: 'rgba(220, 38, 38, 0.4)',
  },
  rsvpButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  rsvpButtonTextAccepted: {
    color: '#ffffff',
  },
  rsvpButtonTextAcceptedInactive: {
    color: '#166534',
  },
  rsvpButtonTextDeclined: {
    color: '#ffffff',
  },
  rsvpButtonTextDeclinedInactive: {
    color: '#dc2626',
  },
  // Text input styles
  textInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    backgroundColor: '#ffffff',
    padding: 12,
    fontSize: 14,
    minHeight: 80,
  },
  // Host styles
  hostContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  hostInfo: {
    flex: 1,
  },
  hostName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  hostRole: {
    fontSize: 14,
    color: '#6b7280',
  },
  // Event details styles
  eventIntro: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  eventDetail: {
    fontSize: 14,
    color: '#374151',
    marginTop: 12,
    lineHeight: 20,
  },
  eventDetailLabel: {
    fontWeight: '700',
  },
  // Items tab styles
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  itemMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 8,
  },
  itemCount: {
    fontSize: 12,
    color: '#6b7280',
  },
  perGuestTag: {
    backgroundColor: '#eef2ff',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  perGuestText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4338ca',
  },
  claimButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },
  claimButtonActive: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  claimButtonComplete: {
    backgroundColor: '#16a34a',
    borderColor: 'transparent',
  },
  claimButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
  },
  claimButtonTextComplete: {
    color: '#ffffff',
    fontWeight: '700',
  },
  completeText: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '600',
    color: '#16a34a',
  },
  qtyBtn: {
    height: 32,
    width: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e5e7eb',
  },
  qtyBtnText: {
    fontSize: 16,
    fontWeight: '900',
    color: '#111827',
  },
  progress: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#e5e7eb',
    overflow: 'hidden',
  },
  progressFill: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10b981',
  },
  // Participants tab styles
  participantsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    backgroundColor: '#ffffff',
  },
  filterButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  inviteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#2563eb',
    marginLeft: 'auto',
  },
  inviteButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  participantCard: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 4,
  },
  participantInfo: {
    flex: 1,
  },
  participantName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },

  // Action buttons styles
  actionsContainer: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    minWidth: 120,
  },
  actionButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 24,
    minWidth: 280,
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
    marginBottom: 24,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  modalButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#2563eb',
    minWidth: 60,
  },
  modalButtonDestructive: {
    backgroundColor: '#dc2626',
  },
  modalButtonCancel: {
    backgroundColor: '#6b7280',
  },
  modalButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalButtonTextDestructive: {
    color: '#ffffff',
  },
  modalButtonTextCancel: {
    color: '#ffffff',
  },
  // AddItemRow styles
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#A22AD0",
  },
  label: {
    fontWeight: "800",
    color: "#3C3C3C",
    marginBottom: 6,
    marginTop: 6,
  },
  inputWrap: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 8,
    paddingLeft: 12,
    overflow: "hidden",
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#A22AD0",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    minHeight: 48,
  },
  addButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    marginLeft: 8,
  },
  // Location styles
  locationHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  locationTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#A22AD0",
    marginLeft: 8,
  },
  locationContent: {
    gap: 8,
  },
  locationText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1f2937",
    lineHeight: 22,
  },
  locationAddress: {
    fontSize: 14,
    color: "#6b7280",
    lineHeight: 20,
  },
  mapButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  mapButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#A22AD0",
    marginLeft: 6,
  },
  // Catalog selection styles
  catalogButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#A22AD0",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  catalogButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 12,
    marginLeft: 4,
  },
  inputText: {
    flex: 1,
    fontSize: 16,
    color: "#111827",
  },
  scrollToTopButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(162, 42, 208, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 8, shadowOffset: { width: 0, height: 4 } },
      android: { elevation: 8 },
    }),
  },
});
