name: REST API E2E

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  rest-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (repo root)
        run: npm ci

      - name: Build server
        working-directory: apps/server
        run: npm run build

      - name: Seed test users
        working-directory: apps/server
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: node scripts/seed-users.mjs

      - name: Start API server
        working-directory: apps/server
        env:
          NODE_ENV: development
          PORT: 3000
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          LEMONSQUEEZY_API_KEY: ${{ secrets.LEMONSQUEEZY_API_KEY }}
          LEMONSQUEEZY_STORE_ID: ${{ secrets.LEMONSQUEEZY_STORE_ID }}
          LEMONSQUEEZY_WEBHOOK_SECRET: ${{ secrets.LEMONSQUEEZY_WEBHOOK_SECRET }}
        run: |
          nohup node dist/src/index.js > server.log 2>&1 & echo $! > server.pid
          sleep 2
          timeout 60 bash -c 'until curl -sf http://localhost:3000/health; do sleep 2; done'

      - name: Run REST E2E cases
        working-directory: apps/server
        env:
          API_BASE: http://localhost:3000/api/v1
          HOST_EMAIL: host@test.dev
          HOST_PASSWORD: password123
          GUEST_EMAIL: participant@test.dev
          GUEST_PASSWORD: password123
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          LEMONSQUEEZY_API_KEY: ${{ secrets.LEMONSQUEEZY_API_KEY }}
          LEMONSQUEEZY_STORE_ID: ${{ secrets.LEMONSQUEEZY_STORE_ID }}
          LEMONSQUEEZY_WEBHOOK_SECRET: ${{ secrets.LEMONSQUEEZY_WEBHOOK_SECRET }}
        run: |
          node tests/rest/cases/auth-and-profile.mjs
          node tests/rest/cases/events-flow.mjs
          node tests/rest/cases/requests-actions.mjs
          node tests/rest/cases/participants-and-items.mjs
          node tests/rest/cases/rebalance.mjs
          node tests/rest/cases/billing-payment-methods.mjs
          node tests/rest/cases/billing-subscriptions.mjs
          node tests/rest/cases/billing-invoices.mjs

      - name: Show server logs on failure
        if: ${{ failure() }}
        working-directory: apps/server
        run: |
          echo '--- server.log (tail) ---'
          tail -n 500 server.log || true

      - name: Stop API server
        if: always()
        working-directory: apps/server
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi

